import FlightCardItem from "../FlightCardItem";

const departureFlights = [
    {
      id: 1,
      Airline: "Indigo",
      FlightNo: "6E-234",
      From: "DEL",
      To: "BOM",
      Departure: "06:30",
      Arrival: "08:45",
      Duration: "2h 15m",
      Fare: "₹4,800",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 2,
      Airline: "Air India",
      FlightNo: "AI-101",
      From: "DEL",
      To: "BOM",
      Departure: "07:15",
      Arrival: "09:35",
      Duration: "2h 20m",
      Fare: "₹5,200",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 3,
      Airline: "Vistara",
      FlightNo: "UK-945",
      From: "DEL",
      To: "BOM",
      Departure: "09:00",
      Arrival: "11:20",
      Duration: "2h 20m",
      Fare: "₹6,100",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 4,
      Airline: "SpiceJet",
      FlightNo: "SG-456",
      From: "DEL",
      To: "BOM",
      Departure: "10:45",
      Arrival: "13:10",
      Duration: "2h 25m",
      Fare: "₹4,500",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 5,
      Airline: "Akasa Air",
      FlightNo: "QP-112",
      From: "DEL",
      To: "BOM",
      Departure: "12:30",
      Arrival: "14:50",
      Duration: "2h 20m",
      Fare: "₹4,200",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 6,
      Airline: "Indigo",
      FlightNo: "6E-782",
      From: "DEL",
      To: "BOM",
      Departure: "14:10",
      Arrival: "16:30",
      Duration: "2h 20m",
      Fare: "₹5,000",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 7,
      Airline: "Air India",
      FlightNo: "AI-665",
      From: "DEL",
      To: "BOM",
      Departure: "15:45",
      Arrival: "18:10",
      Duration: "2h 25m",
      Fare: "₹5,400",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 8,
      Airline: "Vistara",
      FlightNo: "UK-981",
      From: "DEL",
      To: "BOM",
      Departure: "17:20",
      Arrival: "19:40",
      Duration: "2h 20m",
      Fare: "₹6,300",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 9,
      Airline: "SpiceJet",
      FlightNo: "SG-889",
      From: "DEL",
      To: "BOM",
      Departure: "18:55",
      Arrival: "21:20",
      Duration: "2h 25m",
      Fare: "₹4,600",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 10,
      Airline: "Akasa Air",
      FlightNo: "QP-309",
      From: "DEL",
      To: "BOM",
      Departure: "20:30",
      Arrival: "22:50",
      Duration: "2h 20m",
      Fare: "₹4,350",
      Baggage: "15kg",
      Stops: "Non-stop",
    },

    {
      id: 11,
      Airline: "Indigo",
      FlightNo: "6E-543",
      From: "BOM",
      To: "DEL",
      Departure: "06:15",
      Arrival: "08:35",
      Duration: "2h 20m",
      Fare: "₹4,900",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
      id: 12,
      Airline: "Air India",
      FlightNo: "AI-202",
      From: "BOM",
      To: "DEL",
      Departure: "07:50",
      Arrival: "10:10",
      Duration: "2h 20m",
      Fare: "₹5,300",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 13,
      Airline: "Vistara",
      FlightNo: "UK-876",
      From: "BOM",
      To: "DEL",
      Departure: "09:30",
      Arrival: "11:50",
      Duration: "2h 20m",
      Fare: "₹6,200",
      Baggage: "20kg",
      Stops: "Non-stop",
    },
    {
      id: 14,
      Airline: "SpiceJet",
      FlightNo: "SG-332",
      From: "BOM",
      To: "DEL",
      Departure: "11:10",
      Arrival: "13:35",
      Duration: "2h 25m",
      Fare: "₹4,700",
      Baggage: "15kg",
      Stops: "Non-stop",
    },
    {
    id: 15,
    Airline: "Akasa Air",
    FlightNo: "QP-908",
    From: "BOM",
    To: "DEL",
    Departure: "12:45",
    Arrival: "15:05",
    Duration: "2h 20m",
    Fare: "₹4,400",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
];

const returnFlights = [
  {
    id: 16,
    Airline: "Indigo",
    FlightNo: "6E-998",
    From: "BOM",
    To: "DEL",
    Departure: "14:30",
    Arrival: "16:55",
    Duration: "2h 25m",
    Fare: "₹5,100",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 17,
    Airline: "Air India",
    FlightNo: "AI-778",
    From: "BOM",
    To: "DEL",
    Departure: "16:10",
    Arrival: "18:35",
    Duration: "2h 25m",
    Fare: "₹5,500",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 18,
    Airline: "Vistara",
    FlightNo: "UK-654",
    From: "BOM",
    To: "DEL",
    Departure: "17:55",
    Arrival: "20:15",
    Duration: "2h 20m",
    Fare: "₹6,350",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 19,
    Airline: "SpiceJet",
    FlightNo: "SG-144",
    From: "BOM",
    To: "DEL",
    Departure: "19:30",
    Arrival: "21:55",
    Duration: "2h 25m",
    Fare: "₹4,800",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 20,
    Airline: "Akasa Air",
    FlightNo: "QP-511",
    From: "BOM",
    To: "DEL",
    Departure: "21:10",
    Arrival: "23:30",
    Duration: "2h 20m",
    Fare: "₹4,500",
    Baggage: "15kg",
    Stops: "Non-stop",
  },

  {
    id: 21,
    Airline: "Indigo",
    FlightNo: "6E-321",
    From: "BLR",
    To: "DEL",
    Departure: "05:50",
    Arrival: "08:35",
    Duration: "2h 45m",
    Fare: "₹5,600",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 22,
    Airline: "Air India",
    FlightNo: "AI-990",
    From: "BLR",
    To: "DEL",
    Departure: "09:10",
    Arrival: "11:55",
    Duration: "2h 45m",
    Fare: "₹6,100",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 23,
    Airline: "Vistara",
    FlightNo: "UK-432",
    From: "BLR",
    To: "DEL",
    Departure: "12:00",
    Arrival: "14:45",
    Duration: "2h 45m",
    Fare: "₹6,800",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 24,
    Airline: "SpiceJet",
    FlightNo: "SG-765",
    From: "BLR",
    To: "DEL",
    Departure: "15:20",
    Arrival: "18:05",
    Duration: "2h 45m",
    Fare: "₹5,400",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 25,
    Airline: "Akasa Air",
    FlightNo: "QP-600",
    From: "BLR",
    To: "DEL",
    Departure: "18:40",
    Arrival: "21:25",
    Duration: "2h 45m",
    Fare: "₹5,100",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 26,
    Airline: "Indigo",
    FlightNo: "6E-119",
    From: "DEL",
    To: "BLR",
    Departure: "06:10",
    Arrival: "08:55",
    Duration: "2h 45m",
    Fare: "₹5,700",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 27,
    Airline: "Air India",
    FlightNo: "AI-556",
    From: "DEL",
    To: "BLR",
    Departure: "09:45",
    Arrival: "12:30",
    Duration: "2h 45m",
    Fare: "₹6,200",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 28,
    Airline: "Vistara",
    FlightNo: "UK-777",
    From: "DEL",
    To: "BLR",
    Departure: "13:15",
    Arrival: "16:00",
    Duration: "2h 45m",
    Fare: "₹6,900",
    Baggage: "20kg",
    Stops: "Non-stop",
  },
  {
    id: 29,
    Airline: "SpiceJet",
    FlightNo: "SG-888",
    From: "DEL",
    To: "BLR",
    Departure: "17:05",
    Arrival: "19:50",
    Duration: "2h 45m",
    Fare: "₹5,500",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
  {
    id: 30,
    Airline: "Akasa Air",
    FlightNo: "QP-901",
    From: "DEL",
    To: "BLR",
    Departure: "20:40",
    Arrival: "23:25",
    Duration: "2h 45m",
    Fare: "₹5,200",
    Baggage: "15kg",
    Stops: "Non-stop",
  },
];

const FlightCard = () => {
  return (
    <div className="w-full h-full box-border grid grid-cols-2">
      <div>
        <h1 className="text-black font-semibold text-[23px]">
          Departure Flights
        </h1>
        <ul className="list-none">
            {departureFlights.map((eachFlight) => (
                <FlightCardItem key={eachFlight.id} flightDetails={eachFlight} />
            ))}
        </ul>
      </div>
      <div>
        <h1 className="text-black font-semibold text-[23px]">Return Flights</h1>
        <ul className="list-none">
            {returnFlights.map((eachFlight) => (
                <FlightCardItem key={eachFlight.id} flightDetails={eachFlight} />
            ))}
        </ul>
      </div>
    </div>
  );
};

export default FlightCard;
